### ISSUE TITLE
Infografía 

### ISSUE THREAD

**Issue by JeroRoque** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-JeroRoque#1]
[El_Lenguaje_TypeScript_Jeronima_Roque.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-JeroRoque/files/15204763/El_Lenguaje_TypeScript_Jeronima_Roque.pdf)

**Comment by Nelsy21** [comment]
20/20 calificado conforme a la rúbrica.
Buen trabajo.

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
